#  **Dooki Processing**

In [256]:
import pandas as pd
import numpy as np

In [257]:
df_doki = pd.read_csv('/content/processed_dataset_final.csv')
df_doki

/tmp/ipykernel_1741/4176640539.py:1: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df_doki = pd.read_csv('/content/processed_dataset_final.csv')

,postId,pageName,url,time,timestamp,text,likes,comments,shares,topReactionsCount,facebookId_post,media,isVideo,viewsCount,commentUrl,commentId,date,Comment_Text,likesCount,Sentiment_Score
0,625312393573422,DookkiVietnam,https://www.facebook.com/DookkiVietnam/posts/p...,2025-03-02T03:56:06.000Z,2025-03-02 03:56:06,🐔,313,38.0,4,4,100082839990680,No Media,0,0.0,https://www.facebook.com/DookkiVietnam/posts/p...,Y29tbWVudDo2MjUzMTIzOTM1NzM0MjJfNjIzNDM1OTY2OT...,2025-03-02T04:07:59.000Z,Mỗi ngày 1 con gà hơ hơ,6.0,Neutral
1,625312393573422,DookkiVietnam,https://www.facebook.com/DookkiVietnam/posts/p...,2025-03-02T03:56:06.000Z,2025-03-02 03:56:06,🐔,313,38.0,4,4,100082839990680,No Media,0,0.0,https://www.facebook.com/DookkiVietnam/posts/p...,Y29tbWVudDo2MjUzMTIzOTM1NzM0MjJfMTMxNTM5MTA0Mz...,2025-03-02T04:02:16.000Z,đầu gà chiên à shop,2.0,Neutral
2,625312393573422,DookkiVietnam,https://www.facebook.com/DookkiVietnam/posts/p...,2025-03-02T03:56:06.000Z,2025-03-02 03:56:06,🐔,313,38.0,4,4,100082839990680,No Media,0,0.0,https://www.facebook.com/DookkiVietnam/posts/p...,Y29tbWVudDo2MjUzMTIzOTM1NzM0MjJfMTAxNDk4NjQzNz...,2025-03-02T05:10:58.000Z,Em sẽ ko nói là nãy ngồi ăn ở Vincom phạm hùng...,0.0,Neutral
3,625312393573422,DookkiVietnam,https://www.facebook.com/DookkiVietnam/posts/p...,2025-03-02T03:56:06.000Z,2025-03-02 03:56:06,🐔,313,38.0,4,4,100082839990680,No Media,0,0.0,https://www.facebook.com/DookkiVietnam/posts/p...,Y29tbWVudDo2MjUzMTIzOTM1NzM0MjJfMjE0MTUzNDE1Nj...,2025-03-02T03:59:07.000Z,Cái dì nữa dợ Đầu gà chiên Mào gà sốt,3.0,Neutral
4,625312393573422,DookkiVietnam,https://www.facebook.com/DookkiVietnam/posts/p...,2025-03-02T03:56:06.000Z,2025-03-02 03:56:06,🐔,313,38.0,4,4,100082839990680,No Media,0,0.0,https://www.facebook.com/DookkiVietnam/posts/p...,Y29tbWVudDo2MjUzMTIzOTM1NzM0MjJfMTAzMjA1NzAwNT...,2025-03-02T05:07:13.000Z,Sale sủng gì chưa người đẹp,1.0,Neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45447,2246213638982091,DookkiVietnam,https://www.facebook.com/DookkiVietnam/videos/...,2018-11-17T07:49:07.000Z,2018-11-17 07:49:07,📣 🎊 🎉 18H00 17 11 2018 GRAND OPENING DOOKKI VI...,111,367.0,20,2,100082839990680,[{'thumbnail': 'https://scontent.famd1-3.fna.f...,1,12901.0,https://www.facebook.com/DookkiVietnam/videos/...,Y29tbWVudDoyMjQ2MjEzNjM4OTgyMDkxXzIyNDcxODg5OT...,2018-11-18T17:49:46.000Z,Hồ Thị Minh Tâm khỏi tập gym c,0,Neutral
45448,2246213638982091,DookkiVietnam,https://www.facebook.com/DookkiVietnam/videos/...,2018-11-17T07:49:07.000Z,2018-11-17 07:49:07,📣 🎊 🎉 18H00 17 11 2018 GRAND OPENING DOOKKI VI...,111,367.0,20,2,100082839990680,[{'thumbnail': 'https://scontent.famd1-3.fna.f...,1,12901.0,https://www.facebook.com/DookkiVietnam/videos/...,Y29tbWVudDoyMjQ2MjEzNjM4OTgyMDkxXzIyNDcxOTEwND...,2018-11-18T17:51:50.000Z,Thành Nhân aaaaaaaaa thèm,0,Neutral
45449,2246213638982091,DookkiVietnam,https://www.facebook.com/DookkiVietnam/videos/...,2018-11-17T07:49:07.000Z,2018-11-17 07:49:07,📣 🎊 🎉 18H00 17 11 2018 GRAND OPENING DOOKKI VI...,111,367.0,20,2,100082839990680,[{'thumbnail': 'https://scontent.famd1-3.fna.f...,1,12901.0,https://www.facebook.com/DookkiVietnam/videos/...,Y29tbWVudDoyMjQ2MjEzNjM4OTgyMDkxXzIyNDc0NzYxOD...,2018-11-19T05:19:15.000Z,Lâm Hiếu KiênNgọc Ngân 3 tính tiền 2 nè các em...,1,Neutral
45450,2246213638982091,DookkiVietnam,https://www.facebook.com/DookkiVietnam/videos/...,2018-11-17T07:49:07.000Z,2018-11-17 07:49:07,📣 🎊 🎉 18H00 17 11 2018 GRAND OPENING DOOKKI VI...,111,367.0,20,2,100082839990680,[{'thumbnail': 'https://scontent.famd1-3.fna.f...,1,12901.0,https://www.facebook.com/DookkiVietnam/videos/...,Y29tbWVudDoyMjQ2MjEzNjM4OTgyMDkxXzIyNDc1MzI3OT...,2018-11-19T07:39:49.000Z,Phương Lan Hương Nguyên Trần Bách Hợp ms ra ở ...,0,Neutral
45451,2246213638982091,DookkiVietnam,https://www.facebook.com/DookkiVietnam/videos/...,2018-11-17T07:49:07.000Z,2018-11-17 07:49:07,📣 🎊 🎉 18H00 17 11 2018 GRAND OPENING DOOKKI VI...,111,367.0,20,2,100082839990680,[{'thumbnail': 'https://scontent.famd1-3.fna.f...,1,12901.0,https://www.facebook.com/DookkiVietnam/videos/...,Y29tbWVudDoyMjQ2MjEzNjM4OTgyMDkxXzIyNDYzODc4Mz...,2018-11-17T13:21:50.000Z,Chan Trang Liên Trần Khánh Linh chời ơi chải n...,2,Neutral

In [258]:
columns_to_drop = ['facebookId_post', 'media', 'commentUrl', 'url']
df_doki_cleaned = df_doki.drop(columns=columns_to_drop)

print(f"Columns dropped: {columns_to_drop}")
display(df_doki_cleaned.head())

Columns dropped: ['facebookId_post', 'media', 'commentUrl', 'url']

,postId,pageName,time,timestamp,text,likes,comments,shares,topReactionsCount,isVideo,viewsCount,commentId,date,Comment_Text,likesCount,Sentiment_Score
0,625312393573422,DookkiVietnam,2025-03-02T03:56:06.000Z,2025-03-02 03:56:06,🐔,313,38.0,4,4,0,0.0,Y29tbWVudDo2MjUzMTIzOTM1NzM0MjJfNjIzNDM1OTY2OT...,2025-03-02T04:07:59.000Z,Mỗi ngày 1 con gà hơ hơ,6.0,Neutral
1,625312393573422,DookkiVietnam,2025-03-02T03:56:06.000Z,2025-03-02 03:56:06,🐔,313,38.0,4,4,0,0.0,Y29tbWVudDo2MjUzMTIzOTM1NzM0MjJfMTMxNTM5MTA0Mz...,2025-03-02T04:02:16.000Z,đầu gà chiên à shop,2.0,Neutral
2,625312393573422,DookkiVietnam,2025-03-02T03:56:06.000Z,2025-03-02 03:56:06,🐔,313,38.0,4,4,0,0.0,Y29tbWVudDo2MjUzMTIzOTM1NzM0MjJfMTAxNDk4NjQzNz...,2025-03-02T05:10:58.000Z,Em sẽ ko nói là nãy ngồi ăn ở Vincom phạm hùng...,0.0,Neutral
3,625312393573422,DookkiVietnam,2025-03-02T03:56:06.000Z,2025-03-02 03:56:06,🐔,313,38.0,4,4,0,0.0,Y29tbWVudDo2MjUzMTIzOTM1NzM0MjJfMjE0MTUzNDE1Nj...,2025-03-02T03:59:07.000Z,Cái dì nữa dợ Đầu gà chiên Mào gà sốt,3.0,Neutral
4,625312393573422,DookkiVietnam,2025-03-02T03:56:06.000Z,2025-03-02 03:56:06,🐔,313,38.0,4,4,0,0.0,Y29tbWVudDo2MjUzMTIzOTM1NzM0MjJfMTAzMjA1NzAwNT...,2025-03-02T05:07:13.000Z,Sale sủng gì chưa người đẹp,1.0,Neutral

In [259]:
duplicate_postids_count = df_doki_cleaned['postId'].duplicated().sum()
print(f"Number of duplicate 'postId' values: {duplicate_postids_count}")

Number of duplicate 'postId' values: 42989

In [260]:
missing_data_count = df_doki_cleaned.isnull().sum()
print("Missing data count per column:")
print(missing_data_count)

Missing data count per column:
postId                 0
pageName               0
time                   0
timestamp              0
text                   0
likes                  0
comments               0
shares                 0
topReactionsCount      0
isVideo                0
viewsCount             0
commentId            222
date                 222
Comment_Text         109
likesCount           222
Sentiment_Score      109
dtype: int64

In [261]:
bins = [0, 10, 50, 100, 500, 1000, 5000, 10000, 100000]

df_doki_cleaned['likes_range'] = pd.cut(df_doki_cleaned['likes'], bins=bins)

pd.crosstab(df_doki_cleaned['likes_range'], df_doki_cleaned['topReactionsCount'])

topReactionsCount   1     2     3     4     5     6     7
likes_range
(50, 100]          33   730   791   429    40    27     0
(100, 500]         23  1439  2939  4709  4276  1948   498
(500, 1000]         0   100   635  1363  3032  3603  1277
(1000, 5000]        0    40    66   541  2571  6586  4556
(5000, 10000]       0     0     0    20   191   985  1142
(10000, 100000]     0     0     0     0    60   260   542

# Spicy box Processing

In [262]:
df_spicy= pd.read_excel('/content/spicybox_post.xlsx')
df_spicy

,Media,pageName,user/id,user/name,link,timestamp,text,topReactionsCount,viewsCount,shares,comments,url,facebookUrl,inputUrl,isVideo,time,feedbackId,facebookId,likes,postId
0,NaN,spicyboxvn,100076026161990,SPICY BOX,NaN,1741008011,"Hôm nay ngày 3/3, người thứ 3 hiện lên khi bạn...",2,NaN,0,111.0,https://www.facebook.com/spicyboxvn/posts/pfbi...,https://www.facebook.com/spicyboxvn,https://www.facebook.com/spicyboxvn,NaN,2025-03-03T13:20:11.000Z,ZmVlZGJhY2s6NjUxMjUzNzQ3NDE4ODI1,100076026161990,28,651253747418825
1,Video,spicyboxvn,100076026161990,SPICY BOX,NaN,1740927158,Thử đăng giờ này xem mấy sốp có thèm #SPICYBOX,4,5361.0,1,33.0,https://www.facebook.com/reel/1375177936946722/,https://www.facebook.com/spicyboxvn,https://www.facebook.com/spicyboxvn,True,2025-03-02T14:52:38.000Z,ZmVlZGJhY2s6NjUwNTk3NzY0MTUxMDkw,100076026161990,93,650597764151090
2,Photo,spicyboxvn,100076026161990,SPICY BOX,https://bit.ly/4060uJ0,1740835803,"Ở ĐÂU CÓ GRABFOOD, Ở ĐÓ CÓ VOUCHER GIẢM 20% \...",7,NaN,9,54.0,https://www.facebook.com/spicyboxvn/posts/pfbi...,https://www.facebook.com/spicyboxvn,https://www.facebook.com/spicyboxvn,NaN,2025-03-01T13:30:03.000Z,ZmVlZGJhY2s6NjQ5Nzg5NTE0MjMxOTE1,100076026161990,640,649789514231915
3,NaN,spicyboxvn,100076026161990,SPICY BOX,NaN,1740749404,Bánh bao chấm sữa không phải là món gì quá mớ...,2,NaN,3,44.0,https://www.facebook.com/spicyboxvn/posts/pfbi...,https://www.facebook.com/spicyboxvn,https://www.facebook.com/spicyboxvn,NaN,2025-02-28T13:30:04.000Z,ZmVlZGJhY2s6NjQ5MDM1MzE0MzA3MzM1,100076026161990,47,649035314307335
4,NaN,spicyboxvn,100076026161990,SPICY BOX,NaN,1740663002,Mẹo đi ăn lẩu giá rẻ: kiếm đứa bạn có thẻ VIP ...,4,NaN,2,31.0,https://www.facebook.com/spicyboxvn/posts/pfbi...,https://www.facebook.com/spicyboxvn,https://www.facebook.com/spicyboxvn,NaN,2025-02-27T13:30:02.000Z,ZmVlZGJhY2s6NjQ4MjU1MTAxMDUyMDIz,100076026161990,69,648255101052023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,NaN,spicyboxvn,100076026161990,SPICY BOX,NaN,1661433956,Chúc bạn nhìn thấy post này lúc đang đói bụng ...,3,NaN,1,35.0,https://www.facebook.com/spicyboxvn/posts/pfbi...,https://www.facebook.com/spicyboxvn,https://www.facebook.com/spicyboxvn,NaN,2022-08-25T13:25:56.000Z,ZmVlZGJhY2s6Mzk5MDE0MTAzNzg3NjkxNA==,100076026161990,22,3990141037876914
1422,NaN,spicyboxvn,100076026161990,SPICY BOX,NaN,1661347800,Tháng 9 sẽ có nhiều tin bùng nổ lắm đây. Các b...,2,NaN,0,6.0,https://www.facebook.com/spicyboxvn/posts/pfbi...,https://www.facebook.com/spicyboxvn,https://www.facebook.com/spicyboxvn,NaN,2022-08-24T13:30:00.000Z,ZmVlZGJhY2s6Mzk4OTIxMjYyMTMwMzA4OQ==,100076026161990,28,3989212621303089
1423,Photo,spicyboxvn,100076026161990,SPICY BOX,NaN,1661261403,"MỪNG KHAI TRƯƠNG CHI NHÁNH VẠN HẠNH MALL, AI ...",4,NaN,0,22.0,https://www.facebook.com/spicyboxvn/posts/pfbi...,https://www.facebook.com/spicyboxvn,https://www.facebook.com/spicyboxvn,NaN,2022-08-23T13:30:03.000Z,ZmVlZGJhY2s6Mzk4ODQ1OTc2NDcxMTcwOA==,100076026161990,77,3988459764711708
1424,NaN,spicyboxvn,100076026161990,SPICY BOX,NaN,1661175002,Chi nhánh Vạn Hạnh Mall ngày hôm qua.\nCảm ơn ...,3,NaN,2,40.0,https://www.facebook.com/spicyboxvn/posts/pfbi...,https://www.facebook.com/spicyboxvn,https://www.facebook.com/spicyboxvn,NaN,2022-08-22T13:30:02.000Z,ZmVlZGJhY2s6Mzk4NzYxMDk1ODEyOTkyMg==,100076026161990,139,3987610958129922
1425,NaN,spicyboxvn,100076026161990,SPICY BOX,https://bit.ly/3vHuTif,1661088602,Mừng #BLACKPINK đạt 100 triệu lượt xem cho #...,3,NaN,1,20.0,https://www.facebook.com/spicyboxvn/posts/pfbi...,https://www.facebook.com/spicyboxvn,https://www.facebook.com/spicyboxvn,NaN,2022-08-21T13:30:02.000Z,ZmVlZGJhY2s6Mzk4NjgwMjk2NDg3NzM4OA==,100076026161990,23,3986802964877388

In [263]:
columns_to_drop_spicy = ['Media', 'user/id', 'user/name', 'url', 'link', 'facebookUrl', 'inputUrl', 'facebookId', 'feedbackId']
df_spicy_cleaned = df_spicy.drop(columns=columns_to_drop_spicy)

print(f"Columns dropped: {columns_to_drop_spicy}")
display(df_spicy_cleaned.head())

Columns dropped: ['Media', 'user/id', 'user/name', 'url', 'link', 'facebookUrl', 'inputUrl', 'facebookId', 'feedbackId']

,pageName,timestamp,text,topReactionsCount,viewsCount,shares,comments,isVideo,time,likes,postId
0,spicyboxvn,1741008011,"Hôm nay ngày 3/3, người thứ 3 hiện lên khi bạn...",2,NaN,0,111.0,NaN,2025-03-03T13:20:11.000Z,28,651253747418825
1,spicyboxvn,1740927158,Thử đăng giờ này xem mấy sốp có thèm #SPICYBOX,4,5361.0,1,33.0,True,2025-03-02T14:52:38.000Z,93,650597764151090
2,spicyboxvn,1740835803,"Ở ĐÂU CÓ GRABFOOD, Ở ĐÓ CÓ VOUCHER GIẢM 20% \...",7,NaN,9,54.0,NaN,2025-03-01T13:30:03.000Z,640,649789514231915
3,spicyboxvn,1740749404,Bánh bao chấm sữa không phải là món gì quá mớ...,2,NaN,3,44.0,NaN,2025-02-28T13:30:04.000Z,47,649035314307335
4,spicyboxvn,1740663002,Mẹo đi ăn lẩu giá rẻ: kiếm đứa bạn có thẻ VIP ...,4,NaN,2,31.0,NaN,2025-02-27T13:30:02.000Z,69,648255101052023

In [264]:
spicy_missing_data_count = df_spicy_cleaned.isnull().sum()
print("Missing data count per column:")
print(spicy_missing_data_count)

Missing data count per column:
pageName                0
timestamp               0
text                    2
topReactionsCount       0
viewsCount           1257
shares                  0
comments               58
isVideo              1257
time                    0
likes                   0
postId                  0
dtype: int64

In [265]:
columns_to_fill_with_zero = ['viewsCount', 'comments', 'isVideo']
for col in columns_to_fill_with_zero:
    df_spicy_cleaned[col] = df_spicy_cleaned[col].fillna(0)

# Convert 'isVideo' column to numeric (0 or 1)
df_spicy_cleaned['isVideo'] = df_spicy_cleaned['isVideo'].astype(int)

print(f"Missing values in columns {columns_to_fill_with_zero} filled with 0.")
display(df_spicy_cleaned.head())

Missing values in columns ['viewsCount', 'comments', 'isVideo'] filled with 0.

,pageName,timestamp,text,topReactionsCount,viewsCount,shares,comments,isVideo,time,likes,postId
0,spicyboxvn,1741008011,"Hôm nay ngày 3/3, người thứ 3 hiện lên khi bạn...",2,0.0,0,111.0,0,2025-03-03T13:20:11.000Z,28,651253747418825
1,spicyboxvn,1740927158,Thử đăng giờ này xem mấy sốp có thèm #SPICYBOX,4,5361.0,1,33.0,1,2025-03-02T14:52:38.000Z,93,650597764151090
2,spicyboxvn,1740835803,"Ở ĐÂU CÓ GRABFOOD, Ở ĐÓ CÓ VOUCHER GIẢM 20% \...",7,0.0,9,54.0,0,2025-03-01T13:30:03.000Z,640,649789514231915
3,spicyboxvn,1740749404,Bánh bao chấm sữa không phải là món gì quá mớ...,2,0.0,3,44.0,0,2025-02-28T13:30:04.000Z,47,649035314307335
4,spicyboxvn,1740663002,Mẹo đi ăn lẩu giá rẻ: kiếm đứa bạn có thẻ VIP ...,4,0.0,2,31.0,0,2025-02-27T13:30:02.000Z,69,648255101052023

In [266]:
spicy_missing_data_count_after_fill = df_spicy_cleaned[columns_to_fill_with_zero].isnull().sum()
print("Missing data count per column after filling:")
print(spicy_missing_data_count_after_fill)

Missing data count per column after filling:
viewsCount    0
comments      0
isVideo       0
dtype: int64

In [267]:
df_spicy_cleaned['text'] = df_spicy_cleaned['text'].fillna('no content')
print("Missing values in 'text' column filled with 'no content'.")
display(df_spicy_cleaned.head())

Missing values in 'text' column filled with 'no content'.

,pageName,timestamp,text,topReactionsCount,viewsCount,shares,comments,isVideo,time,likes,postId
0,spicyboxvn,1741008011,"Hôm nay ngày 3/3, người thứ 3 hiện lên khi bạn...",2,0.0,0,111.0,0,2025-03-03T13:20:11.000Z,28,651253747418825
1,spicyboxvn,1740927158,Thử đăng giờ này xem mấy sốp có thèm #SPICYBOX,4,5361.0,1,33.0,1,2025-03-02T14:52:38.000Z,93,650597764151090
2,spicyboxvn,1740835803,"Ở ĐÂU CÓ GRABFOOD, Ở ĐÓ CÓ VOUCHER GIẢM 20% \...",7,0.0,9,54.0,0,2025-03-01T13:30:03.000Z,640,649789514231915
3,spicyboxvn,1740749404,Bánh bao chấm sữa không phải là món gì quá mớ...,2,0.0,3,44.0,0,2025-02-28T13:30:04.000Z,47,649035314307335
4,spicyboxvn,1740663002,Mẹo đi ăn lẩu giá rẻ: kiếm đứa bạn có thẻ VIP ...,4,0.0,2,31.0,0,2025-02-27T13:30:02.000Z,69,648255101052023

In [268]:
df_spicy_cleaned['topReactionsCount'].unique()

array([2, 4, 7, 3, 5, 6, 1])

In [269]:
bins = [0, 10, 50, 100, 500, 1000, 5000, 10000, 100000]

df_spicy_cleaned['likes_range'] = pd.cut(df_spicy_cleaned['likes'], bins=bins)

pd.crosstab(df_spicy_cleaned['likes_range'], df_spicy_cleaned['topReactionsCount'])

topReactionsCount   1    2    3    4    5   6   7
likes_range
(0, 10]             6    6    0    0    0   0   0
(10, 50]           19  150   68   19    3   0   0
(50, 100]           0  100  106   54   19   1   1
(100, 500]          0   76  156  184  115  36   3
(500, 1000]         0    1   18   36   43  38  14
(1000, 5000]        0    0    2   12   37  38  29
(5000, 10000]       0    0    0    0    8   8   5
(10000, 100000]     0    0    0    0    0   6   9

# joseon

In [270]:
df_joseon = pd.read_excel('/content/joseon.xlsx')
df_joseon

,Media,postId,isVideo,text,comments,viewsCount,facebookId,user/id,user/name,likes,timestamp,facebookUrl,time,url,shares,link
0,NaN,495677243599621,NaN,LÊN KẾ HOẠCH 8/3 CHO CÁC NGƯỜI ĐẸP GÌ CHƯA CÁC...,NaN,NaN,100094720480711,100094720480711,Joseon Tteokbokki,12,1741341609,https://www.facebook.com/profile.php?id=100094...,2025-03-07T10:00:09.000Z,https://www.facebook.com/permalink.php?story_f...,0,NaN
1,NaN,495090363658309,NaN,NHỮNG “ĐOÁ HOA” “NGON MẮT” TẠI JOSEON\n\nJoseo...,1.0,NaN,100094720480711,100094720480711,Joseon Tteokbokki,13,1741269243,https://www.facebook.com/profile.php?id=100094...,2025-03-06T13:54:03.000Z,https://www.facebook.com/permalink.php?story_f...,2,NaN
2,NaN,493614677139211,NaN,"ĐẦU THÁNG NGÁN CƠM NHÀ, THÈM CƠM CUỘN VÀ CƠM T...",NaN,NaN,100094720480711,100094720480711,Joseon Tteokbokki,9,1741089656,https://www.facebook.com/profile.php?id=100094...,2025-03-04T12:00:56.000Z,https://www.facebook.com/permalink.php?story_f...,0,NaN
3,Photo,490811120752900,NaN,"KỂ TỪ NGÀY 30/2, TÔI SẼ…\n • Quyết tâm thoát k...",101.0,NaN,100094720480711,100094720480711,Joseon Tteokbokki,141,1740749162,https://www.facebook.com/profile.php?id=100094...,2025-02-28T13:26:02.000Z,https://www.facebook.com/permalink.php?story_f...,1,NaN
4,NaN,489428794224466,NaN,THẮNG ĐỜI 1-0 LÀ KHI…\n\n • Sớm phát hiện ra m...,102.0,NaN,100094720480711,100094720480711,Joseon Tteokbokki,136,1740579245,https://www.facebook.com/profile.php?id=100094...,2025-02-26T14:14:05.000Z,https://www.facebook.com/permalink.php?story_f...,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308,Photo,110572465443436,NaN,Nghe nói trời mưa ăn lẩu Tteobokki siêu cay th...,5.0,NaN,100094720480711,100094720480711,Joseon Tteokbokki,4,1689847402,https://www.facebook.com/profile.php?id=100094...,2023-07-20T10:03:22.000Z,https://www.facebook.com/permalink.php?story_f...,1,NaN
309,Photo,109344512232898,NaN,"Cứ ăn đi cho đời nó khỏe, rồi lúc béo tha hồ t...",NaN,NaN,100094720480711,100094720480711,Joseon Tteokbokki,4,1689735796,https://www.facebook.com/profile.php?id=100094...,2023-07-19T03:03:16.000Z,https://www.facebook.com/permalink.php?story_f...,1,NaN
310,Photo,108404638993552,NaN,Không biết mọi người nghe tin gì chưa ạ \nTin ...,NaN,NaN,100094720480711,100094720480711,Joseon Tteokbokki,2,1689651703,https://www.facebook.com/profile.php?id=100094...,2023-07-18T03:41:43.000Z,https://www.facebook.com/permalink.php?story_f...,2,NaN
311,Photo,106531515847531,NaN,NaN,NaN,NaN,100094720480711,100094720480711,Joseon Tteokbokki,0,1689478895,https://www.facebook.com/profile.php?id=100094...,2023-07-16T03:41:35.000Z,https://www.facebook.com/permalink.php?story_f...,0,NaN
312,Photo,105734699260546,NaN,NaN,NaN,NaN,100094720480711,100094720480711,Joseon Tteokbokki,5,1689401688,https://www.facebook.com/profile.php?id=100094...,2023-07-15T06:14:48.000Z,https://www.facebook.com/permalink.php?story_f...,0,NaN

In [271]:
display(df_joseon.head())

,Media,postId,isVideo,text,comments,viewsCount,facebookId,user/id,user/name,likes,timestamp,facebookUrl,time,url,shares,link
0,NaN,495677243599621,NaN,LÊN KẾ HOẠCH 8/3 CHO CÁC NGƯỜI ĐẸP GÌ CHƯA CÁC...,NaN,NaN,100094720480711,100094720480711,Joseon Tteokbokki,12,1741341609,https://www.facebook.com/profile.php?id=100094...,2025-03-07T10:00:09.000Z,https://www.facebook.com/permalink.php?story_f...,0,NaN
1,NaN,495090363658309,NaN,NHỮNG “ĐOÁ HOA” “NGON MẮT” TẠI JOSEON\n\nJoseo...,1.0,NaN,100094720480711,100094720480711,Joseon Tteokbokki,13,1741269243,https://www.facebook.com/profile.php?id=100094...,2025-03-06T13:54:03.000Z,https://www.facebook.com/permalink.php?story_f...,2,NaN
2,NaN,493614677139211,NaN,"ĐẦU THÁNG NGÁN CƠM NHÀ, THÈM CƠM CUỘN VÀ CƠM T...",NaN,NaN,100094720480711,100094720480711,Joseon Tteokbokki,9,1741089656,https://www.facebook.com/profile.php?id=100094...,2025-03-04T12:00:56.000Z,https://www.facebook.com/permalink.php?story_f...,0,NaN
3,Photo,490811120752900,NaN,"KỂ TỪ NGÀY 30/2, TÔI SẼ…\n • Quyết tâm thoát k...",101.0,NaN,100094720480711,100094720480711,Joseon Tteokbokki,141,1740749162,https://www.facebook.com/profile.php?id=100094...,2025-02-28T13:26:02.000Z,https://www.facebook.com/permalink.php?story_f...,1,NaN
4,NaN,489428794224466,NaN,THẮNG ĐỜI 1-0 LÀ KHI…\n\n • Sớm phát hiện ra m...,102.0,NaN,100094720480711,100094720480711,Joseon Tteokbokki,136,1740579245,https://www.facebook.com/profile.php?id=100094...,2025-02-26T14:14:05.000Z,https://www.facebook.com/permalink.php?story_f...,1,NaN

In [272]:
missing_data_joseon = df_joseon.isnull().sum()
print("Missing data count per column in df_joseon:")
print(missing_data_joseon)

Missing data count per column in df_joseon:
Media          112
postId           0
isVideo        232
text            17
comments        77
viewsCount     232
facebookId       0
user/id          0
user/name        0
likes            0
timestamp        0
facebookUrl      0
time             0
url              0
shares           0
link           303
dtype: int64

In [273]:
columns_to_drop_joseon = ['link', 'url', 'facebookUrl', 'user/id', 'user/name', 'facebookId', 'Media']
df_joseon = df_joseon.drop(columns=columns_to_drop_joseon)

print(f"Columns dropped: {columns_to_drop_joseon}")
display(df_joseon.head())

Columns dropped: ['link', 'url', 'facebookUrl', 'user/id', 'user/name', 'facebookId', 'Media']

,postId,isVideo,text,comments,viewsCount,likes,timestamp,time,shares
0,495677243599621,NaN,LÊN KẾ HOẠCH 8/3 CHO CÁC NGƯỜI ĐẸP GÌ CHƯA CÁC...,NaN,NaN,12,1741341609,2025-03-07T10:00:09.000Z,0
1,495090363658309,NaN,NHỮNG “ĐOÁ HOA” “NGON MẮT” TẠI JOSEON\n\nJoseo...,1.0,NaN,13,1741269243,2025-03-06T13:54:03.000Z,2
2,493614677139211,NaN,"ĐẦU THÁNG NGÁN CƠM NHÀ, THÈM CƠM CUỘN VÀ CƠM T...",NaN,NaN,9,1741089656,2025-03-04T12:00:56.000Z,0
3,490811120752900,NaN,"KỂ TỪ NGÀY 30/2, TÔI SẼ…\n • Quyết tâm thoát k...",101.0,NaN,141,1740749162,2025-02-28T13:26:02.000Z,1
4,489428794224466,NaN,THẮNG ĐỜI 1-0 LÀ KHI…\n\n • Sớm phát hiện ra m...,102.0,NaN,136,1740579245,2025-02-26T14:14:05.000Z,1

In [274]:
columns_to_fill_with_zero_joseon = ['isVideo', 'comments', 'viewsCount']
for col in columns_to_fill_with_zero_joseon:
    df_joseon[col] = df_joseon[col].fillna(0)

# Convert 'isVideo' column to numeric (0 or 1)
df_joseon['isVideo'] = df_joseon['isVideo'].astype(int)

print(f"Missing values in columns {columns_to_fill_with_zero_joseon} filled with 0.")
display(df_joseon.head())

Missing values in columns ['isVideo', 'comments', 'viewsCount'] filled with 0.

,postId,isVideo,text,comments,viewsCount,likes,timestamp,time,shares
0,495677243599621,0,LÊN KẾ HOẠCH 8/3 CHO CÁC NGƯỜI ĐẸP GÌ CHƯA CÁC...,0.0,0.0,12,1741341609,2025-03-07T10:00:09.000Z,0
1,495090363658309,0,NHỮNG “ĐOÁ HOA” “NGON MẮT” TẠI JOSEON\n\nJoseo...,1.0,0.0,13,1741269243,2025-03-06T13:54:03.000Z,2
2,493614677139211,0,"ĐẦU THÁNG NGÁN CƠM NHÀ, THÈM CƠM CUỘN VÀ CƠM T...",0.0,0.0,9,1741089656,2025-03-04T12:00:56.000Z,0
3,490811120752900,0,"KỂ TỪ NGÀY 30/2, TÔI SẼ…\n • Quyết tâm thoát k...",101.0,0.0,141,1740749162,2025-02-28T13:26:02.000Z,1
4,489428794224466,0,THẮNG ĐỜI 1-0 LÀ KHI…\n\n • Sớm phát hiện ra m...,102.0,0.0,136,1740579245,2025-02-26T14:14:05.000Z,1

In [275]:
df_joseon['text'] = df_joseon['text'].fillna('no content')
print("Missing values in 'text' column filled with 'no content'.")
display(df_joseon.head())

Missing values in 'text' column filled with 'no content'.

,postId,isVideo,text,comments,viewsCount,likes,timestamp,time,shares
0,495677243599621,0,LÊN KẾ HOẠCH 8/3 CHO CÁC NGƯỜI ĐẸP GÌ CHƯA CÁC...,0.0,0.0,12,1741341609,2025-03-07T10:00:09.000Z,0
1,495090363658309,0,NHỮNG “ĐOÁ HOA” “NGON MẮT” TẠI JOSEON\n\nJoseo...,1.0,0.0,13,1741269243,2025-03-06T13:54:03.000Z,2
2,493614677139211,0,"ĐẦU THÁNG NGÁN CƠM NHÀ, THÈM CƠM CUỘN VÀ CƠM T...",0.0,0.0,9,1741089656,2025-03-04T12:00:56.000Z,0
3,490811120752900,0,"KỂ TỪ NGÀY 30/2, TÔI SẼ…\n • Quyết tâm thoát k...",101.0,0.0,141,1740749162,2025-02-28T13:26:02.000Z,1
4,489428794224466,0,THẮNG ĐỜI 1-0 LÀ KHI…\n\n • Sớm phát hiện ra m...,102.0,0.0,136,1740579245,2025-02-26T14:14:05.000Z,1

In [276]:
df_joseon['pageName'] = 'joseon'

In [277]:
bins = [0, 50, 100, 500, 1000, 5000, float('inf')]
labels = [2, 3, 4, 5, 6, 7]

df_joseon['topReactionsCount'] = pd.cut(
    df_joseon['likes'],
    bins=bins,
    labels=labels,
    include_lowest=True # Added to include 0 in the lowest bin
).astype(float).fillna(0).astype(int)

# joppii

In [278]:
df_joppii = pd.read_excel('/content/joppii.xlsx')

In [279]:
missing_data_joppii = df_joppii.isnull().sum()
print("Missing data count per column in df_joppii:")
print(missing_data_joppii)

Missing data count per column in df_joppii:
Media         522
user/id         0
user/name       0
shares          0
link          780
postId          0
text           35
comments      174
viewsCount    870
likes           0
timestamp       0
time            0
url             0
dtype: int64

In [280]:
df_joppii = df_joppii.rename(columns={'isvideo': 'isVideo'})
print("Column 'isvideo' renamed to 'isVideo' in df_joppii.")
display(df_joppii.head())

Column 'isvideo' renamed to 'isVideo' in df_joppii.

,Media,user/id,user/name,shares,link,postId,text,comments,viewsCount,likes,timestamp,time,url
0,Photo,100069048300038,Joopii VietNam,2,NaN,969909715320630,Nhà hàng JOOPII ( hệ thống Lẩu buffet TokbokkT...,2.0,NaN,40,1740981820,2025-03-03T06:03:40.000Z,https://www.facebook.com/joopiivietnam/posts/p...
1,NaN,100069048300038,Joopii VietNam,8,NaN,969125842065684,[GRAND OPENING] CHECK IN JOOPII BIÊN HOÀ NHẬN ...,66.0,NaN,227,1740888003,2025-03-02T04:00:03.000Z,https://www.facebook.com/joopiivietnam/posts/p...
2,Photo,100069048300038,Joopii VietNam,1,NaN,966853622292906,"Feniu Biên Hòa có hóng không, chứ ad mất ăn mấ...",19.0,NaN,34,1740630498,2025-02-27T04:28:18.000Z,https://www.facebook.com/joopiivietnam/posts/p...
3,Photo,100069048300038,Joopii VietNam,1,NaN,966087915702810,"Hú hồn chim én, hên là đi với nhỏ bạn chứ khôn...",14.0,NaN,42,1740542401,2025-02-26T04:00:01.000Z,https://www.facebook.com/joopiivietnam/posts/p...
4,Video,100069048300038,Joopii VietNam,10,NaN,965302412448027,Mỳ gà nướng phô mai kéo sợi ngon đỉnh nóc kịch...,7.0,6251.0,161,1740460376,2025-02-25T05:12:56.000Z,https://www.facebook.com/reel/1098142055402286/

In [281]:
columns_to_drop_joppii = ['url', 'link', 'Media', 'user/id', 'user/name']
df_joppii = df_joppii.drop(columns=columns_to_drop_joppii)

# Create 'isvideo' column: 1 if 'viewsCount' is not NaN, 0 if it is NaN
df_joppii['isvideo'] = df_joppii['viewsCount'].notna().astype(int)

print(f"Columns dropped: {columns_to_drop_joppii}")
print("'isvideo' column created based on 'viewsCount' presence.")
display(df_joppii.head())

Columns dropped: ['url', 'link', 'Media', 'user/id', 'user/name']
'isvideo' column created based on 'viewsCount' presence.

,shares,postId,text,comments,viewsCount,likes,timestamp,time,isvideo
0,2,969909715320630,Nhà hàng JOOPII ( hệ thống Lẩu buffet TokbokkT...,2.0,NaN,40,1740981820,2025-03-03T06:03:40.000Z,0
1,8,969125842065684,[GRAND OPENING] CHECK IN JOOPII BIÊN HOÀ NHẬN ...,66.0,NaN,227,1740888003,2025-03-02T04:00:03.000Z,0
2,1,966853622292906,"Feniu Biên Hòa có hóng không, chứ ad mất ăn mấ...",19.0,NaN,34,1740630498,2025-02-27T04:28:18.000Z,0
3,1,966087915702810,"Hú hồn chim én, hên là đi với nhỏ bạn chứ khôn...",14.0,NaN,42,1740542401,2025-02-26T04:00:01.000Z,0
4,10,965302412448027,Mỳ gà nướng phô mai kéo sợi ngon đỉnh nóc kịch...,7.0,6251.0,161,1740460376,2025-02-25T05:12:56.000Z,1

In [282]:
missing_data_joppii_after_cleaning = df_joppii.isnull().sum()
print("Missing data count per column in df_joppii after cleaning:")
print(missing_data_joppii_after_cleaning)

Missing data count per column in df_joppii after cleaning:
shares          0
postId          0
text           35
comments      174
viewsCount    870
likes           0
timestamp       0
time            0
isvideo         0
dtype: int64

In [283]:
columns_to_fill_with_zero_joppii = ['comments', 'viewsCount']
for col in columns_to_fill_with_zero_joppii:
    df_joppii[col] = df_joppii[col].fillna(0)

df_joppii['text'] = df_joppii['text'].fillna('no content')

print(f"Missing values in columns {columns_to_fill_with_zero_joppii} filled with 0.")
print("Missing values in 'text' column filled with 'no content'.")
display(df_joppii.head())

Missing values in columns ['comments', 'viewsCount'] filled with 0.
Missing values in 'text' column filled with 'no content'.

,shares,postId,text,comments,viewsCount,likes,timestamp,time,isvideo
0,2,969909715320630,Nhà hàng JOOPII ( hệ thống Lẩu buffet TokbokkT...,2.0,0.0,40,1740981820,2025-03-03T06:03:40.000Z,0
1,8,969125842065684,[GRAND OPENING] CHECK IN JOOPII BIÊN HOÀ NHẬN ...,66.0,0.0,227,1740888003,2025-03-02T04:00:03.000Z,0
2,1,966853622292906,"Feniu Biên Hòa có hóng không, chứ ad mất ăn mấ...",19.0,0.0,34,1740630498,2025-02-27T04:28:18.000Z,0
3,1,966087915702810,"Hú hồn chim én, hên là đi với nhỏ bạn chứ khôn...",14.0,0.0,42,1740542401,2025-02-26T04:00:01.000Z,0
4,10,965302412448027,Mỳ gà nướng phô mai kéo sợi ngon đỉnh nóc kịch...,7.0,6251.0,161,1740460376,2025-02-25T05:12:56.000Z,1

In [284]:
missing_data_joppii_final = df_joppii.isnull().sum()
print("Missing data count per column in df_joppii after final cleaning:")
print(missing_data_joppii_final)

Missing data count per column in df_joppii after final cleaning:
shares        0
postId        0
text          0
comments      0
viewsCount    0
likes         0
timestamp     0
time          0
isvideo       0
dtype: int64

In [285]:
bins = [0, 50, 100, 500, 1000, 5000, float('inf')]
labels = [2, 3, 4, 5, 6, 7]

df_joppii['topReactionsCount'] = pd.cut(
    df_joppii['likes'],
    bins=bins,
    labels=labels,
    include_lowest=True # Added to include 0 in the lowest bin
).astype(float).fillna(0).astype(int)

In [286]:
df_joppii['pageName'] = 'joppii'

In [287]:
display(df_joppii.head())

,shares,postId,text,comments,viewsCount,likes,timestamp,time,isvideo,topReactionsCount,pageName
0,2,969909715320630,Nhà hàng JOOPII ( hệ thống Lẩu buffet TokbokkT...,2.0,0.0,40,1740981820,2025-03-03T06:03:40.000Z,0,2,joppii
1,8,969125842065684,[GRAND OPENING] CHECK IN JOOPII BIÊN HOÀ NHẬN ...,66.0,0.0,227,1740888003,2025-03-02T04:00:03.000Z,0,4,joppii
2,1,966853622292906,"Feniu Biên Hòa có hóng không, chứ ad mất ăn mấ...",19.0,0.0,34,1740630498,2025-02-27T04:28:18.000Z,0,2,joppii
3,1,966087915702810,"Hú hồn chim én, hên là đi với nhỏ bạn chứ khôn...",14.0,0.0,42,1740542401,2025-02-26T04:00:01.000Z,0,2,joppii
4,10,965302412448027,Mỳ gà nướng phô mai kéo sợi ngon đỉnh nóc kịch...,7.0,6251.0,161,1740460376,2025-02-25T05:12:56.000Z,1,4,joppii

# Xử lý dữ liệu text và thêm 2 cột phân loại content và số lượng từ trong text.

In [288]:
import re

def process_text_features(df):
    # --- 1. Đếm số lượng từ (Word Count) ---
    def count_words(text):
        t = str(text)
        if t.lower() == 'no content' or t.strip() == "":
            return 0
        return len(t.split())

    df['word_count'] = df['text'].apply(count_words)

    # --- 2. Phân loại nội dung (Content Category) ---
    def classify_content(text):
        t = str(text).lower()

        # Xử lý trường hợp không có nội dung chữ
        if t == 'no content' or t.strip() == "":
            return 'Media Only'

        # Nhóm 1: Khuyến mãi / Giá cả
        if any(w in t for w in ['khuyến mãi', 'ưu đãi', 'giảm', '139k', 'giá', 'voucher', 'buffet', 'chỉ từ', 'sale']):
            return 'Promotion'

        # Nhóm 2: Tương tác / Game
        elif any(w in t for w in ['minigame', 'tặng', 'quà', 'may mắn', 'thử thách', 'tag', 'comment', 'nhận ngay']):
            return 'Engagement'

        # Nhóm 3: Món ăn / Review (Đặc thù F&B)
        elif any(w in t for w in ['ngon', 'vị', 'gà', 'lẩu', 'tokbokki', 'phô mai', 'món mới', 'menu', 'thưởng thức']):
            return 'Food/Product'

        # Nhóm 4: Tin tức / Khai trương
        elif any(w in t for w in ['khai trương', 'chi nhánh', 'địa chỉ', 'tầng', 'thông báo', 'tuyển dụng']):
            return 'News/Branch'

        # Còn lại: Thương hiệu / Khác
        else:
            return 'Branding/Others'

    df['content_category'] = df['text'].apply(classify_content)
    return df

In [289]:
# Áp dụng cho từng bảng của bạn
df_doki_cleaned = process_text_features(df_doki_cleaned)
df_spicy_cleaned = process_text_features(df_spicy_cleaned)
df_joseon = process_text_features(df_joseon)
df_joppii = process_text_features(df_joppii)

print("Đã thêm cột word_count và content_category thành công!")

Đã thêm cột word_count và content_category thành công!

In [290]:
display(df_doki_cleaned.tail(1))

,postId,pageName,time,timestamp,text,likes,comments,shares,topReactionsCount,isVideo,viewsCount,commentId,date,Comment_Text,likesCount,Sentiment_Score,likes_range,word_count,content_category
45451,2246213638982091,DookkiVietnam,2018-11-17T07:49:07.000Z,2018-11-17 07:49:07,📣 🎊 🎉 18H00 17 11 2018 GRAND OPENING DOOKKI VI...,111,367.0,20,2,1,12901.0,Y29tbWVudDoyMjQ2MjEzNjM4OTgyMDkxXzIyNDYzODc4Mz...,2018-11-17T13:21:50.000Z,Chan Trang Liên Trần Khánh Linh chời ơi chải n...,2,Neutral,"(100, 500]",151,Promotion

In [291]:
display(df_spicy_cleaned.tail(1))

,pageName,timestamp,text,topReactionsCount,viewsCount,shares,comments,isVideo,time,likes,postId,likes_range,word_count,content_category
1425,spicyboxvn,1661088602,Mừng #BLACKPINK đạt 100 triệu lượt xem cho #...,3,0.0,1,20.0,0,2022-08-21T13:30:02.000Z,23,3986802964877388,"(10, 50]",72,Promotion

In [292]:
display(df_joseon.tail(1))

,postId,isVideo,text,comments,viewsCount,likes,timestamp,time,shares,pageName,topReactionsCount,word_count,content_category
312,105734699260546,0,no content,0.0,0.0,5,1689401688,2023-07-15T06:14:48.000Z,0,joseon,2,0,Media Only

In [293]:
display(df_joppii.tail(1))

,shares,postId,text,comments,viewsCount,likes,timestamp,time,isvideo,topReactionsCount,pageName,word_count,content_category
963,0,103960667742178,no content,0.0,0.0,0,1574151488,2019-11-19T08:18:08.000Z,0,2,joppii,0,Media Only

# Tạo Dimtime

In [294]:
import pandas as pd

# 1. Tạo dãy thời gian từ 2018 đến giữa 2025 (tần suất theo Giờ 'H')
time_rng = pd.date_range(start='2018-01-01', end='2025-06-30 23:00:00', freq='H')

# 2. Tạo DataFrame
dim_time = pd.DataFrame(time_rng, columns=['timestamp'])

# 3. Trích xuất các cột thời gian cơ bản
dim_time['full_date'] = dim_time['timestamp'].dt.date
dim_time['year'] = dim_time['timestamp'].dt.year
dim_time['month'] = dim_time['timestamp'].dt.month
dim_time['day'] = dim_time['timestamp'].dt.day
dim_time['hour'] = dim_time['timestamp'].dt.hour
dim_time['day_of_week'] = dim_time['timestamp'].dt.day_name()

# 4. THÊM CỘT QUÝ (Quarter)
# Kết quả sẽ là 1, 2, 3, 4
dim_time['quarter'] = dim_time['timestamp'].dt.quarter

# 5. THÊM CỘT TYPE DAY (Weekday/Weekend)
# dt.dayofweek trả về 0-4 là từ Thứ 2 đến Thứ 6, 5-6 là Thứ 7 & CN
dim_time['type_day'] = dim_time['timestamp'].dt.dayofweek.apply(
    lambda x: 'Weekend' if x >= 5 else 'Weekday'
)

# 6. Phân loại "Buổi" (Daypart Analysis)
def phan_loai_buoi(h):
    if 5 <= h < 11: return 'Morning'
    elif 11 <= h < 14: return 'Noon'
    elif 14 <= h < 17: return 'Afternoon'
    elif 17 <= h < 22: return 'Evening'
    else: return 'Night'

dim_time['day_part'] = dim_time['hour'].apply(phan_loai_buoi)

# Hiển thị thử 5 dòng ngẫu nhiên để kiểm tra
print(dim_time.sample(5))

                timestamp   full_date  year  month  day  hour day_of_week  \
1372  2018-02-27 04:00:00  2018-02-27  2018      2   27     4     Tuesday
23408 2020-09-02 08:00:00  2020-09-02  2020      9    2     8   Wednesday
39549 2022-07-06 21:00:00  2022-07-06  2022      7    6    21   Wednesday
10724 2019-03-23 20:00:00  2019-03-23  2019      3   23    20    Saturday
11771 2019-05-06 11:00:00  2019-05-06  2019      5    6    11      Monday

       quarter type_day day_part
1372         1  Weekday    Night
23408        3  Weekday  Morning
39549        3  Weekday  Evening
10724        1  Weekend  Evening
11771        2  Weekday     Noon

/tmp/ipykernel_1741/3837903445.py:4: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  time_rng = pd.date_range(start='2018-01-01', end='2025-06-30 23:00:00', freq='H')

# Tạo Fact/Dim Table

In [295]:
import pandas as pd

# 1. Đồng nhất tên cột isVideo
df_joppii = df_joppii.rename(columns={'isvideo': 'isVideo'})

# 2. Danh sách cột cho bảng Fact (Đã LOẠI BỎ cột 'text')
fact_columns = [
    'postId', 'pageName', 'timestamp', 'likes', 'comments',
    'shares', 'topReactionsCount', 'isVideo', 'viewsCount',
    'word_count', 'content_category'
]

# 3. Gộp 4 bảng thành Fact_Posts
fact_posts = pd.concat([
    df_doki_cleaned[fact_columns],
    df_spicy_cleaned[fact_columns],
    df_joseon[fact_columns],
    df_joppii[fact_columns]
], ignore_index=True)

# --- 4. XỬ LÝ TIMESTAMP (Hàm fix cũ của chúng ta) ---
def fix_timestamp(ts):
    try:
        return pd.to_datetime(ts)
    except:
        try:
            val = float(ts)
            if val > 9999999999:
                return pd.to_datetime(val, unit='ms')
            return pd.to_datetime(val, unit='s')
        except:
            return pd.NaT

fact_posts['timestamp'] = fact_posts['timestamp'].apply(fix_timestamp)
fact_posts = fact_posts.dropna(subset=['timestamp'])

# Tạo khóa nối với bảng Dim_Time và chuẩn hóa isVideo
fact_posts['timestamp_link'] = fact_posts['timestamp'].dt.floor('H')
fact_posts['isVideo'] = pd.to_numeric(fact_posts['isVideo'], errors='coerce').fillna(0).astype(int)

# --- 5. XUẤT CÁC BẢNG RA CSV CHO POWER BI ---

# File 1: Fact_Posts (Gọn nhẹ, không có text)
fact_posts.to_csv('Fact_Posts.csv', index=False, encoding='utf-8-sig')

# File 2: Dim_Time (Bảng thời gian bạn đã tạo)
dim_time.to_csv('Dim_Time.csv', index=False, encoding='utf-8-sig')

# File 3: Dim_Pages (Phân loại Brand)
dim_pages = pd.DataFrame({'pageName': fact_posts['pageName'].unique()})
dim_pages['Brand_Group'] = dim_pages['pageName'].apply(
    lambda x: 'Dookki' if 'doki' in str(x).lower() or 'dookki' in str(x).lower() else 'Competitor'
)
dim_pages.to_csv('Dim_Pages.csv', index=False, encoding='utf-8-sig')

# File 4: Dim_Dookki_Details (Giữ lại Comment_Text và Sentiment cho Dookki)
dim_dookki_details = df_doki_cleaned[
    ['commentId', 'postId', 'Comment_Text', 'Sentiment_Score', 'date', 'likesCount']
].dropna(subset=['commentId'])
dim_dookki_details.to_csv('Dim_Dookki_Details.csv', index=False, encoding='utf-8-sig')

print("✅ Đã xử lý xong! Bảng Fact giờ đây chỉ chứa dữ liệu số và các category.")
display(fact_posts.head())

/tmp/ipykernel_1741/1797880183.py:38: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  fact_posts['timestamp_link'] = fact_posts['timestamp'].dt.floor('H')

✅ Đã xử lý xong! Bảng Fact giờ đây chỉ chứa dữ liệu số và các category.

,postId,pageName,timestamp,likes,comments,shares,topReactionsCount,isVideo,viewsCount,word_count,content_category,timestamp_link
0,625312393573422,DookkiVietnam,2025-03-02 03:56:06,313,38.0,4,4,0,0.0,1,Branding/Others,2025-03-02 03:00:00
1,625312393573422,DookkiVietnam,2025-03-02 03:56:06,313,38.0,4,4,0,0.0,1,Branding/Others,2025-03-02 03:00:00
2,625312393573422,DookkiVietnam,2025-03-02 03:56:06,313,38.0,4,4,0,0.0,1,Branding/Others,2025-03-02 03:00:00
3,625312393573422,DookkiVietnam,2025-03-02 03:56:06,313,38.0,4,4,0,0.0,1,Branding/Others,2025-03-02 03:00:00
4,625312393573422,DookkiVietnam,2025-03-02 03:56:06,313,38.0,4,4,0,0.0,1,Branding/Others,2025-03-02 03:00:00

In [296]:
# --- 2. TẠO BẢNG DIM_DOOKKI_DETAILS (Bảng chi tiết cho Dookki) ---

# Tách riêng phần comment và sentiment của Dookki để tránh làm loãng bảng Fact
dim_dookki_details = df_doki_cleaned[
    ['commentId', 'postId', 'Comment_Text', 'Sentiment_Score', 'date', 'likesCount']
].dropna(subset=['commentId']).copy()

In [297]:
# --- 3. TẠO BẢNG DIM_PAGES (Thông tin thương hiệu) ---

dim_pages = pd.DataFrame({
    'pageName': fact_posts['pageName'].unique()
})

# Phân loại Brand để báo cáo (Target vs Competitor)
dim_pages['brand_label'] = dim_pages['pageName'].apply(
    lambda x: 'Dookki' if 'doki' in str(x).lower() or 'dookki' in str(x).lower() else x
)
dim_pages['is_target'] = dim_pages['brand_label'].apply(lambda x: 1 if x == 'Dookki' else 0)

# Xuất fact/dim ra csv

In [298]:
import pandas as pd

# 1. XUẤT BẢNG FACT (Bảng chính)
# Đảm bảo các cột số liệu không bị lỗi định dạng khi vào Power BI
fact_posts.to_csv('Fact_Posts.csv', index=False, encoding='utf-8-sig')

# 2. XUẤT BẢNG DIM TIME (Bảng thời gian)
# Bảng này cực kỳ quan trọng để tạo báo cáo theo Thứ/Ngày/Giờ/Lịch âm
dim_time.to_csv('Dim_Time.csv', index=False, encoding='utf-8-sig')

# 3. XUẤT BẢNG DIM PAGES (Bảng danh mục Brand)
dim_pages = pd.DataFrame({'pageName': fact_posts['pageName'].unique()})
dim_pages['Brand_Group'] = dim_pages['pageName'].apply(
    lambda x: 'Dookki' if 'doki' in str(x).lower() or 'dookki' in str(x).lower() else 'Competitor'
)
dim_pages.to_csv('Dim_Pages.csv', index=False, encoding='utf-8-sig')

# 4. XUẤT BẢNG DIM DOOKKI DETAILS (Bảng chuyên sâu Sentiment)
# Dùng để Join với Fact_Posts qua postId khi cần phân tích cảm xúc
dim_dookki_details = df_doki_cleaned[
    ['commentId', 'postId', 'Comment_Text', 'Sentiment_Score', 'date', 'likesCount']
].dropna(subset=['commentId'])
dim_dookki_details.to_csv('Dim_Dookki_Details.csv', index=False, encoding='utf-8-sig')

print("✅ Đã xuất 4 file CSV thành công! Bạn hãy tải chúng về để nạp vào Power BI.")

✅ Đã xuất 4 file CSV thành công! Bạn hãy tải chúng về để nạp vào Power BI.